#!/usr/bin/perl

# $Id: mkcd,v 1.4 2006/09/08 16:07:59 swain Exp $

# hello sailor

use strict;
use warnings;

# make a cd command like this:                                                                               
# cd /mnt/nfs-1/mpa1/web/k/ka/kam/kamisah.myphotodevel.com/web                                               

my $root = '/mnt/cel-1/vol01';

if ($ARGV[0]) {

    my ($a, $b, $c, $d, $e, $x) = split //, $ARGV[0], 6;

    print "cd $root/$a/$a$b/$a$b$c/$a$b$c$d/$a$b$c$d$e/$ARGV[0]\n";

} else {
    print "cd /opt/mpa/custom-sites/myphotoalbum/";
}


# $Log: mkcd,v $
# Revision 1.4  2006/09/08 16:07:59  swain
# typo
#
# Revision 1.3  2006/09/08 16:07:17  swain
# updated the path to the interpreter
#
# Revision 1.2  2005/04/22 19:59:34  swain
# it's log, it's log, it's better than bad it's good
#
