#!/usr/bin/perl

# hello sailor

use strict;
use warnings;

# make a cd command like this:                                                                               
# cd /mnt/nfs-1/mpa1/web/k/ka/kam/kamisah.myphotodevel.com/web                                               

my $root = '/mnt/fast/vol01';

if ($ARGV[0]) {

    my ($a, $b, $c, $d, $e, $x) = split //, $ARGV[0], 6;

    print "cd $root/$a/$a$b/$a$b$c/$a$b$c$d/$a$b$c$d$e/$ARGV[0]\n";

} else {
    print "cd /opt/mpa/custom-sites/myphotoalbum/";
}
