#!/usr/bin/perl -w

# This script parses the mpa.orders.log files and extracts the
# transfer time for images to District's FTP server.

# Aug 2007, SW
# $Id: cull_upload_times.pl,v 1.1 2007/08/24 14:06:47 swain Exp $

# usage: ./cull_upload_times.pl mpa.orders.log.*

# create a lookup table for months
%months = qw(Jan 01 Feb 02 Mar 03 Apr 04 May 05 Jun 06 Jul 07 Aug 08 Sep 09 Oct 10 Nov 11 Dec 12);

open OUTFILE, "> xfer.sql" or die $!;
print OUTFILE "-- Autogenerated by script $0 on ", scalar(localtime), " by $ENV{USER}\n";
while (<DATA>) { print OUTFILE; }


foreach $file (@ARGV) {
    print "Doing $file...\n";
    open INFILE, "< $file" or die "Can't open log file '$file': $!\n";

THISLOG:

    while ($line = <INFILE>) {
        if ($line =~ / Uploading /) {
            $nextline = <INFILE>;
            if ($nextline =~ /xfer/) {
                #print OUTFILE $line;
                #print OUTFILE $nextline;
                chomp $line;
                (undef, $date) = split / at /, $line;
                next THISLOG unless $date;
                @f = split / +/, $date;
                #for ($x=0; $x < $#f+1; $x++) { print "$x:$f[$x];"; }
                #print "\n";
                # 0:Sun   1:Dec   2:3   3:20:00:54   4:2006 
                $dow  = $f[0];
                if (length($f[2]) == 1) { $f[2] = "0$f[2]"; }
                $date = "$f[4]-$months{$f[1]}-$f[2] $f[3]";


                $nextline =~ m/\| (\d+) \| ([0-9.]+) \|/;
                next THISLOG unless ($date && $dow && $1 && $2);
                #print OUTFILE "$1\t$2\t$date\t$dow\n";
                print OUTFILE "INSERT INTO ofs_upload_times (id, bytes, seconds, uploaddate, day_of_week)\n";
                print OUTFILE "VALUES(NULL, $1, $2, '$date', '$dow');\n";
                #last if $x++ > 20;
            }
        }
    }
}

# $Log: cull_upload_times.pl,v $
# Revision 1.1  2007/08/24 14:06:47  swain
# Parse the ofs logs for the upload times of individual image files; generates SQL statements.
#


__END__
drop table if exists ofs_upload_times;
create table ofs_upload_times (
                               id int auto_increment primary key,
                               bytes int(4),
                               seconds float,
                               uploaddate datetime,
                               day_of_week varchar(3)
                               );



