# Not sure if I got around to using this... I think my idea was to use
# containers to explore newer Perl features instead of installing from
# MacPorts. Nov 2020.

FROM perl:latest

WORKDIR /home/swain
CMD cpan App::cpanminus
CMD cpanm WWW:Mechanize