#!/usr/bin/perl

while ($line = <DATA>) {
    chomp $line;
    $line =~ s/\s//g;
    ($cat, $prod, $id) = split /\s*,\s*/, $line;
    #print "$cat, $prod, $id\n";
    # read in our template file
    if (exists $hash{$id}) {
        next;
    } else {
        print "$cat, $prod, $id\n";
        $hash{$id}++;
    }
    
}

# input data below was made with:
# select category_name, category_member, p.products_id from osc_products_to_categories pc, mpa_products_groupings pg, osc_products p where upper(pg.category_member) = p.constant_name and pc.products_id = p.products_id and pc.categories_id = 20;
# plus some rectangle editing (go emacs!)
# limit yourself to single photo products (i.e. omit stuff like barney dvds)
__END__
justfriends           , frosted_stein        ,        7110 
justfriends           , keepsake_box         ,        7118 
justfriends           , large_canvas         ,        7123 
justfriends           , heavy_white_t_shirts ,        7143 
justfriends           , white_sweatshirt_s   ,        7148 
mugsandmousepads      , mousepad_3mm         ,        7171 
mugsandmousepads      , tiled_mousepad       ,        7170 
justfriends           , coasters_4x4         ,        7111 
spring                , teddy_bear           ,        7127 
spring                , clip_board           ,        7121 
spring                , playing_cards        ,        7124 
spring                , white_steel_mug      ,        7109 
spring                , bbq_apron            ,        7135 
spring                , deluxe_tote_bag      ,        7136 
spring                , golf_towel           ,        7164 
spring                , coasters_4x4         ,        7111 
spring                , keepsake_box         ,        7118 
spring                , pillow_case          ,        7112 
kids                  , teddy_bear           ,        7127 
kids                  , pillow_case          ,        7112 
kids                  , kids_t_shirts        ,        7153 
summer                , deluxe_tote_bag      ,        7136 
summer                , frosted_stein        ,        7110 
summer                , white_t_shirts       ,        7138 
summer                , bbq_apron            ,        7135 
summer                , golf_towel           ,        7164 
summer                , pillow_case          ,        7112 
summer                , coasters_4x4         ,        7111 
summer                , playing_cards        ,        7124 
summer                , clip_board           ,        7121 
mousepads             , mousepad_3mm         ,        7171 
thankyou              , coasters_4x4         ,        7111 
thankyou              , puzzle_252piece      ,        7126 
thankyou              , keepsake_box         ,        7118 
thankyou              , large_canvas         ,        7123 
thankyou              , cutting_board        ,        7120 
thankyou              , frosted_stein        ,        7110 
thankyou              , wall_clock           ,        7119 
popular               , ceramic_black_mug    ,        7105 
popular               , ceramic_mug_11_oz    ,        7103 
popular               , mousepads_8x9        ,        7102 
popular               , ceramic_mug_15_oz    ,        7107 
popular               , tiled_mug_11_oz      ,        7104 
popular               , playing_cards        ,        7124 
popular               , tiled_mug_15_oz      ,        7108 
popular               , white_steel_mug      ,        7109 
popular               , magic_mug            ,        7106 
popular               , puzzle_252piece      ,        7126 
popular               , pillow_case          ,        7112 
popular               , coasters_4x4         ,        7111 
popular               , white_t_shirts       ,        7138 
popular               , keepsake_box         ,        7118 
popular               , deluxe_tote_bag      ,        7136 
popular               , bbq_apron            ,        7135 
anniversary           , small_canvas         ,        7122 
anniversary           , large_canvas         ,        7123 
anniversary           , keepsake_box         ,        7118 
anniversary           , throw_blanket        ,        7113 
anniversary           , wall_clock           ,        7119 
formoms               , keepsake_box         ,        7118 
formoms               , deluxe_tote_bag      ,        7136 
formoms               , clutch_bag           ,        7162 
formoms               , bucket_bag           ,        7163 
formoms               , small_canvas         ,        7122 
formoms               , bbq_apron            ,        7135 
formoms               , wall_clock           ,        7119 
formoms               , pillow_sham          ,        7114 
formoms               , throw_blanket        ,        7113 
formoms               , coasters_4x4         ,        7111 
ornaments             , ornament_snowflake   ,        7117 
ornaments             , ornament_flat        ,        7115 
easter                , teddy_bear           ,        7127 
easter                , clip_board           ,        7121 
easter                , playing_cards        ,        7124 
easter                , white_steel_mug      ,        7109 
easter                , bbq_apron            ,        7135 
easter                , deluxe_tote_bag      ,        7136 
easter                , golf_towel           ,        7164 
easter                , coasters_4x4         ,        7111 
easter                , keepsake_box         ,        7118 
easter                , pillow_case          ,        7112 
graduation            , frosted_stein        ,        7110 
graduation            , playing_cards        ,        7124 
graduation            , coasters_4x4         ,        7111 
graduation            , pillow_case          ,        7112 
prints                , small_canvas         ,        7122 
prints                , large_canvas         ,        7123 
prom                  , frosted_stein        ,        7110 
prom                  , keepsake_box         ,        7118 
prom                  , boxer_shorts         ,        7158 
prom                  , pillow_case          ,        7112 
prom                  , coasters_4x4         ,        7111 
christmas             , keepsake_box         ,        7118 
christmas             , playing_cards        ,        7124 
christmas             , small_canvas         ,        7122 
christmas             , puzzle_252piece      ,        7126 
christmas             , pillow_case          ,        7112 
christmas             , coasters_4x4         ,        7111 
christmas             , bbq_apron            ,        7135 
christmas             , throw_blanket        ,        7113 
christmas             , deluxe_tote_bag      ,        7136 
forpet                , pet_collar           ,        7132 
forpet                , dog_bowl             ,        7134 
partyprops            , heavy_white_t_shirts ,        7143 
partyprops            , coasters_4x4         ,        7111 
partyprops            , playing_cards        ,        7124 
forgrandma            , keepsake_box         ,        7118 
forgrandma            , deluxe_tote_bag      ,        7136 
forgrandma            , large_canvas         ,        7123 
forgrandma            , bbq_apron            ,        7135 
forgrandma            , coasters_4x4         ,        7111 
forgrandma            , white_sweatshirt_s   ,        7148 
forgrandma            , throw_blanket        ,        7113 
forgrandma            , puzzle_252piece      ,        7126 
mugs                  , ceramic_mug_11_oz    ,        7103 
mugs                  , tiled_mug_11_oz      ,        7104 
mugs                  , ceramic_black_mug    ,        7105 
mugs                  , magic_mug            ,        7106 
mugs                  , ceramic_mug_15_oz    ,        7107 
mugs                  , tiled_mug_15_oz      ,        7108 
mugs                  , stainless_travel_mug ,        7169 
mugs                  , frosted_stein        ,        7110 
winter                , playing_cards        ,        7124 
winter                , puzzle_252piece      ,        7126 
winter                , pillow_case          ,        7112 
winter                , coasters_4x4         ,        7111 
winter                , white_t_shirts       ,        7138 
winter                , keepsake_box         ,        7118 
birthday              , playing_cards        ,        7124 
birthday              , coasters_4x4         ,        7111 
birthday              , clutch_bag           ,        7162 
birthday              , deluxe_tote_bag      ,        7136 
birthday              , puzzle_252piece      ,        7126 
birthday              , small_canvas         ,        7122 
fordads               , white_steel_mug      ,        7109 
fordads               , playing_cards        ,        7124 
fordads               , frosted_stein        ,        7110 
fordads               , golf_towel           ,        7164 
fordads               , small_canvas         ,        7122 
fordads               , large_canvas         ,        7123 
fordads               , boxer_shorts         ,        7158 
fordads               , white_t_shirts       ,        7138 
fordads               , white_sweatshirt_s   ,        7148 
fordads               , coasters_4x4         ,        7111 
muggsand mousepds     , gel_mousepad         ,        7172 
under20               , ceramic_mug_11_oz    ,        7103 
under20               , tiled_mug_11_oz      ,        7104 
under20               , ceramic_black_mug    ,        7105 
under20               , girl_bib             ,        7156 
under20               , boy_bib              ,        7157 
apparelandaccessories , bucket_bag           ,        7163 
under20               , ceramic_mug_15_oz    ,        7107 
under20               , tiled_mug_15_oz      ,        7108 
under20               , white_t_shirts       ,        7138 
under20               , kids_t_shirts        ,        7153 
under20               , white_steel_mug      ,        7109 
under20               , ornament_snowflake   ,        7117 
under20               , ornament_flat        ,        7115 
under20               , magic_mug            ,        7106 
apparelandaccessories , bbq_apron            ,        7135 
apparelandaccessories , white_sweatshirt_s   ,        7148 
under20               , teddy_bear           ,        7127 
under20               , pillow_case          ,        7112 
under20               , coasters_4x4         ,        7111 
under20               , frosted_stein        ,        7110 
under20               , golf_towel           ,        7164 
under20               , photo_baseball       ,        7128 
under20               , bbq_apron            ,        7135 
newbaby               , diaper_bag           ,        7137 
newbaby               , teddy_bear           ,        7127 
newbaby               , girl_bib             ,        7156 
newbaby               , boy_bib              ,        7157 
newbaby               , keepsake_box         ,        7118 
newbaby               , small_canvas         ,        7122 
newbaby               , throw_blanket        ,        7113 
newbaby               , deluxe_tote_bag      ,        7136 
forgrandpa            , white_steel_mug      ,        7109 
forgrandpa            , playing_cards        ,        7124 
forgrandpa            , frosted_stein        ,        7110 
forgrandpa            , white_t_shirts       ,        7138 
forgrandpa            , boxer_shorts         ,        7158 
forgrandpa            , white_sweatshirt_s   ,        7148 
forgrandpa            , golf_towel           ,        7164 
newproducts           , clutch_bag           ,        7162 
newproducts           , bucket_bag           ,        7163 
newproducts           , mousepad_3mm         ,        7171 
newproducts           , gel_mousepad         ,        7172 
newproducts           , tiled_mousepad       ,        7170 
mousepads             , mousepads_8x9        ,        7102 
mousepads             , gel_mousepad         ,        7172 
mousepads             , tiled_mousepad       ,        7170 
apparelandaccessories , diaper_bag           ,        7137 
apparelandaccessories , girl_bib             ,        7156 
apparelandaccessories , boy_bib              ,        7157 
apparelandaccessories , clutch_bag           ,        7162 
apparelandaccessories , heavy_white_t_shirts ,        7143 
forher                , deluxe_tote_bag      ,        7136 
forher                , clutch_bag           ,        7162 
forher                , bucket_bag           ,        7163 
forher                , coasters_4x4         ,        7111 
forher                , keepsake_box         ,        7118 
forher                , pillow_case          ,        7112 
forher                , small_canvas         ,        7122 
forher                , throw_blanket        ,        7113 
forher                , bbq_apron            ,        7135 
newyears              , playing_cards        ,        7124 
newyears              , puzzle_252piece      ,        7126 
newyears              , pillow_case          ,        7112 
newyears              , coasters_4x4         ,        7111 
newyears              , white_t_shirts       ,        7138 
newyears              , keepsake_box         ,        7118 
apparel               , white_t_shirts       ,        7138 
apparel               , heavy_white_t_shirts ,        7143 
apparel               , white_sweatshirt_s   ,        7148 
apparel               , kids_t_shirts        ,        7153 
apparel               , deluxe_tote_bag      ,        7136 
apparel               , clutch_bag           ,        7162 
apparel               , bucket_bag           ,        7163 
apparel               , bbq_apron            ,        7135 
apparel               , girl_bib             ,        7156 
apparel               , boy_bib              ,        7157 
apparel               , diaper_bag           ,        7137 
forcouple             , small_canvas         ,        7122 
forcouple             , large_canvas         ,        7123 
forcouple             , keepsake_box         ,        7118 
forcouple             , throw_blanket        ,        7113 
forcouple             , wall_clock           ,        7119 
forcouple             , playing_cards        ,        7124 
forcouple             , cutting_board        ,        7120 
forcouple             , coasters_4x4         ,        7111 
halloween             , puzzle_252piece      ,        7126 
halloween             , large_canvas         ,        7123 
halloween             , teddy_bear           ,        7127 
halloween             , playing_cards        ,        7124 
halloween             , throw_blanket        ,        7113 
halloween             , deluxe_tote_bag      ,        7136 
school                , pillow_case          ,        7112 
school                , throw_blanket        ,        7113 
school                , playing_cards        ,        7124 
school                , frosted_stein        ,        7110 
school                , deluxe_tote_bag      ,        7136 
school                , clip_board           ,        7121 
apparelandaccessories , kids_t_shirts        ,        7153 
school                , coasters_4x4         ,        7111 
forfamily             , throw_blanket        ,        7113 
forfamily             , large_canvas         ,        7123 
forfamily             , small_canvas         ,        7122 
forfamily             , keepsake_box         ,        7118 
forfamily             , wall_clock           ,        7119 
forfamily             , pillow_sham          ,        7114 
mugsandmousepads      , gel_mousepad         ,        7172 
mugsandmousepads      , ceramic_mug_15_oz    ,        7107 
mugsandmousepads      , ceramic_mug_11_oz    ,        7103 
mugsandmousepads      , white_steel_mug      ,        7109 
mugsandmousepads      , mousepads_8x9        ,        7102 
allproducts           , ceramic_mug_11_oz    ,        7103 
allproducts           , ceramic_black_mug    ,        7105 
allproducts           , magic_mug            ,        7106 
allproducts           , ceramic_mug_15_oz    ,        7107 
allproducts           , tiled_mug_15_oz      ,        7108 
allproducts           , frosted_stein        ,        7110 
allproducts           , coasters_4x4         ,        7111 
allproducts           , playing_cards        ,        7124 
allproducts           , puzzle_in_box        ,        7125 
allproducts           , puzzle_252piece      ,        7126 
allproducts           , deluxe_tote_bag      ,        7136 
mugs                  , white_steel_mug      ,        7109 
allproducts           , clutch_bag           ,        7162 
allproducts           , bucket_bag           ,        7163 
allproducts           , diaper_bag           ,        7137 
travel_mugs           , white_steel_mug      ,        7109 
travel_mugs           , stainless_travel_mug ,        7169 
allproducts           , small_canvas         ,        7122 
allproducts           , large_canvas         ,        7123 
allproducts           , keepsake_box         ,        7118 
allproducts           , pillow_case          ,        7112 
allproducts           , throw_blanket        ,        7113 
allproducts           , white_t_shirts       ,        7138 
allproducts           , heavy_white_t_shirts ,        7143 
allproducts           , white_sweatshirt_s   ,        7148 
allproducts           , kids_t_shirts        ,        7153 
allproducts           , girl_bib             ,        7156 
allproducts           , boy_bib              ,        7157 
allproducts           , bbq_apron            ,        7135 
allproducts           , boxer_shorts         ,        7158 
allproducts           , teddy_bear           ,        7127 
allproducts           , golf_towel           ,        7164 
sports_balls          , photo_soccerball     ,        7131 
sports_balls          , photo_minifootball   ,        7130 
sports_balls          , photo_baseball       ,        7128 
sports_balls          , photo_minibasketball ,        7129 
allproducts           , photo_baseball       ,        7128 
allproducts           , photo_minibasketball ,        7129 
allproducts           , photo_minifootball   ,        7130 
allproducts           , photo_soccerball     ,        7131 
apparelandaccessories , deluxe_tote_bag      ,        7136 
apparelandaccessories , white_t_shirts       ,        7138 
mugsandmousepads      , coasters_4x4         ,        7111 
mugsandmousepads      , frosted_stein        ,        7110 
allproducts           , pillow_sham          ,        7114 
allproducts           , wall_clock           ,        7119 
allproducts           , cutting_board        ,        7120 
allproducts           , clip_board           ,        7121 
allproducts           , pet_collar           ,        7132 
allproducts           , dog_bowl             ,        7134 
allproducts           , ornament_snowflake   ,        7117 
allproducts           , ornament_flat        ,        7115 
camp                  , teddy_bear           ,        7127 
camp                  , pillow_case          ,        7112 
camp                  , playing_cards        ,        7124 
camp                  , kids_t_shirts        ,        7153 
camp                  , throw_blanket        ,        7113 
camp                  , photo_soccerball     ,        7131 
camp                  , puzzle_252piece      ,        7126 
camp                  , photo_baseball       ,        7128 
camp                  , photo_minibasketball ,        7129 
camp                  , photo_minifootball   ,        7130 
forhim                , boxer_shorts         ,        7158 
forhim                , playing_cards        ,        7124 
forhim                , frosted_stein        ,        7110 
forhim                , golf_towel           ,        7164 
forhim                , clip_board           ,        7121 
forhim                , pillow_case          ,        7112 
valentines            , keepsake_box         ,        7118 
valentines            , boxer_shorts         ,        7158 
mugsandmousepads      , tiled_mug_11_oz      ,        7104 
valentines            , throw_blanket        ,        7113 
valentines            , large_canvas         ,        7123 
valentines            , pillow_case          ,        7112 
valentines            , teddy_bear           ,        7127 
coasters              , coasters_4x4         ,        7111 
games_and_puzzles     , golf_towel           ,        7164 
games_and_puzzles     , teddy_bear           ,        7127 
games_and_puzzles     , puzzle_in_box        ,        7125 
games_and_puzzles     , playing_cards        ,        7124 
games_and_puzzles     , puzzle_252piece      ,        7126 
games_and_puzzles     , photo_baseball       ,        7128 
games_and_puzzles     , photo_minibasketball ,        7129 
games_and_puzzles     , photo_minifootball   ,        7130 
games_and_puzzles     , photo_soccerball     ,        7131 
games_and_puzzles     , clip_board           ,        7121 
seasonsgreetings      , playing_cards        ,        7124 
mugsandmousepads      , magic_mug            ,        7106 
seasonsgreetings      , small_canvas         ,        7122 
seasonsgreetings      , deluxe_tote_bag      ,        7136 
seasonsgreetings      , puzzle_252piece      ,        7126 
seasonsgreetings      , pillow_case          ,        7112 
seasonsgreetings      , coasters_4x4         ,        7111 
seasonsgreetings      , keepsake_box         ,        7118 
seasonsgreetings      , bbq_apron            ,        7135 
congratulations       , coasters_4x4         ,        7111 
congratulations       , puzzle_252piece      ,        7126 
congratulations       , keepsake_box         ,        7118 
congratulations       , large_canvas         ,        7123 
congratulations       , teddy_bear           ,        7127 
congratulations       , cutting_board        ,        7120 
congratulations       , frosted_stein        ,        7110 
congratulations       , wall_clock           ,        7119 
home_and_office       , pillow_case          ,        7112 
home_and_office       , coasters_4x4         ,        7111 
home_and_office       , keepsake_box         ,        7118 
home_and_office       , bbq_apron            ,        7135 
home_and_office       , frosted_stein        ,        7110 
home_and_office       , wall_clock           ,        7119 
home_and_office       , small_canvas         ,        7122 
home_and_office       , large_canvas         ,        7123 
home_and_office       , throw_blanket        ,        7113 
mugsandmousepads      , stainless_travel_mug ,        7169 
home_and_office       , cutting_board        ,        7120 
home_and_office       , pillow_sham          ,        7114 
home_and_office       , clip_board           ,        7121 
wedding               , small_canvas         ,        7122 
wedding               , large_canvas         ,        7123 
wedding               , keepsake_box         ,        7118 
wedding               , throw_blanket        ,        7113 
wedding               , coasters_4x4         ,        7111 
wedding               , wall_clock           ,        7119 
mugsandmousepads      , tiled_mug_15_oz      ,        7108 
